---
#
# RPi custom setup
#
# account: pi/raspberry
#
# sudo apt-get install xrdp
# sudo apt-get install vnc4server
#
# Need to set up SSH first
# ssh-keygen -t rsa
# ssh-copy-id -i ~/.ssh/id_rsa.pub $remote_user@$remote_host
#
# ansible-playbook main.yml -b
#

- hosts: rpi
  remote_user: pi
  tasks:
  - name: 'Update APT package cache'
    action: apt update_cache=yes

  - name: 'Upgrade APT to the lastest packages'
    action: apt upgrade=safe

  - name: 'Fix up RDP'
    action: apt name=xrdp

  - name: 'Fix up VNC'
    action: apt name=vnc4server

  - name: 'etho0 config'
    lineinfile:
      dest: '/etc/dhcpcd.conf'
      line: 'interface eth0'

  - name: 'IP Address'
    lineinfile:
      dest: '/etc/dhcpcd.conf'
      line: 'static ip_address=172.16.1.8'

  - name: 'Router'
    lineinfile:
      dest: '/etc/dhcpcd.conf'
      line: 'static routers=172.16.1.1'

  - name: 'IP Address'
    lineinfile:
      dest: '/etc/dhcpcd.conf'
      line: 'static domain_name_servers=172.16.1.1'

  - name: 'Reboot'
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: "Wait for Raspberry RPi to come back"
    local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300
    become: false